### ISSUE TITLE
Error when trying to run nav_bar:start

### ISSUE THREAD

**Issue by mthomas-github** [OlegGulevskyy/zendesk-vite-boilerplate#2]
failed to load config from /Users/michaelthomas/Repos/zendesk-vite-boilerplate/packages/nav_bar/vite.config.js
error when starting dev server:
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/michaelthomas/Repos/zendesk-vite-boilerplate/node_modules/@app/zendesk/vite-plugin-inject-zaf-html' is not supported resolving ES modules imported from /Users/michaelthomas/Repos/zendesk-vite-boilerplate/packages/nav_bar/vite.config.js.mjs
Did you mean to import /Users/michaelthomas/Repos/zendesk-vite-boilerplate/packages/zendesk/vite-plugin-inject-zaf-html/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:314:17)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)

**Comment by OlegGulevskyy** [comment]
Have you just cloned the repo and did `yarn` in the root project before trying to run `nav_bar:start` or did you do any changes / modifications?
I can run into the same error if I am modifying current `nav_bar` `vite.config.ts` file
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/43781031/180576345-375babfb-af52-4244-80c5-e649f556692f.png">

Can you please check how your `vite-plugin-inject-zaf-html` is imported? It has to be imported like so
```ts
import * as pluginPkg from "@app/zendesk/vite-plugin-inject-zaf-html/index.js";
```

**Comment by OlegGulevskyy** [comment]
Full import and use is below:

```ts
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import * as pluginPkg from "@app/zendesk/vite-plugin-inject-zaf-html/index.js";
const { injectZafHtmlPlugin } = pluginPkg.default;

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), injectZafHtmlPlugin()],
  base: "./",
  build: {
    outDir: `${process.env.INIT_CWD}/dist/assets/${process.env.ADDON_TYPE}`,
    emptyOutDir: true,
  },
});
```

**Comment by mthomas-github** [comment]
Thanks that worked, I should've looked at your nav_bar example my mistake

**Comment by OlegGulevskyy** [comment]
No worries, glad it is working now!
Svelte is doing things differently when importing the plug-in, not sure exactly why
