### ISSUE TITLE
[DOCUMENTATION] Add section on Parameters

### ISSUE THREAD

**Issue by go4cas** [OlegGulevskyy/zendesk-vite-boilerplate#4]
I often use parameters for my Zendesk apps. During the development cycle, I will add default values for these in a `zclic.apps.config. json` file. This way, the dev server will start up, without prompting for manual entry of the parameters.

I got this working in the boilerplate, by doing the following:
- Under the `/packages/zendesk` folder, open the `manifest.json` file, and add the following section (below are example params - you will replace these with your own):
```json
"parameters": [
    {
      "name": "apiUrl",
      "type": "text",
      "secure": false,
      "required": true
    },
    {
      "name": "apiUser",
      "type": "text",
      "secure": false,
      "required": true
    },
    {
      "name": "apiPassword",
      "type": "password",
      "secure": true,
      "required": true
    }
  ]
```
- Under the `/packages/zendesk` folder, add a new file named `zclic.apps.config. json`, and add your parameters:
```json
{
  "parameters": {
    "apiUrl": "http://api.my-domain-here.com",
    "apiUser": "agent.smith@example.com",
    "apiPassword": "MySuperSecretPwd123$%^"
  }
}
```
- Restart the `zcli` server

**Comment by OlegGulevskyy** [comment]
This is really useful tip! Thanks for sharing!
If you wish, you can add this to the readme description, I will be happy to accept the PR
Or I will add it later myself, up to you :)
