### ISSUE TITLE
Vite Server Port for Vue.js app

### ISSUE THREAD

**Issue by go4cas** [OlegGulevskyy/zendesk-vite-boilerplate#5]
When creating a new vue.js app, using site, under the `packages` folder, site will select a random available port (I think?) for the dev server. For me, the app somehow did not work inside Zendesk Support.

To get it to work correctly, I had to manually add the `server.port` to the `vote.config.js` file:

```javascript
export default defineConfig({
  plugins: [
    vue(),
    injectZafHtmlPlugin(),
  ],
  base: './',
  build: {
    outDir: `${process.env.INIT_CWD}/dist/assets/${process.env.ADDON_TYPE}`,
    emptyOutDir: true,
  },
  server: {
    port: 3000,
  },
})
```

**Comment by OlegGulevskyy** [comment]
Thanks for raising this point!
It's weird that it didn't assign default port (maybe something was already listening on this port for you before?), but I think this is not a "regular" thing that happens on every framework init. However, you should be indeed able to change the port to whatever you want, and this boilerplate has to support it.
I created a PR #6  where I am adding support for customizing the port in the generated manifest file
This way you can set this port to whatever your needs are, and then specify the port in the manifest file, so it doesn't have to be `3000` strictly anymore.

Let me know if this makes sense
